import Foundation
import SwiftProtobuf

// ============================================================
// Manually coded message wrappers for AudioRelay protocol
// ============================================================
// In production, these would be generated by protoc from the .proto file.
// For the MVP, we define key message types manually with proper protobuf
// encoding/decoding using SwiftProtobuf.

/// Wrapper for encoding/decoding AudioRelay messages with length-prefix framing.
enum AudioRelayMessage {
    /// Length prefix in bytes for WebSocket frame framing
    static let lengthPrefixSize = 4

    /// AudioRelay default ports
    enum Ports {
        static let defaultTCP = 59200    // WebSocket control channel
        static let defaultUDP = 59100    // Audio data channel
    }
}

// MARK: - Binary Message Framing

/// Encodes a protobuf message with 4-byte big-endian length prefix
func frameMessage(_ data: Data) -> Data {
    var framed = Data()
    var length = UInt32(data.count).bigEndian
    framed.append(Data(bytes: &length, count: 4))
    framed.append(data)
    return framed
}

/// Reads length-prefixed messages from a data stream.
/// Returns (message, remainingBytes) or nil if incomplete.
func unframeMessage(from data: Data) -> (Data, Data)? {
    guard data.count >= 4 else { return nil }
    let length = data.withUnsafeBytes { $0.load(as: UInt32.self).bigEndian }
    let totalLength = 4 + Int(length)
    guard data.count >= totalLength else { return nil }
    let message = data.subdata(in: 4..<totalLength)
    let remaining = data.subdata(in: totalLength..<data.count)
    return (message, remaining)
}

// MARK: - Handshake Messages

struct ClientHello {
    let clientId: String
    let clientVersion: String
    let os: String
    let osVersion: String
    let features: PlayerFeatures

    func encode() -> Data {
        // Build a simple protobuf-wire-format encoded message
        var data = Data()

        // Field 1: client_id (string)
        data.append(protoFieldString(1, clientId))
        // Field 2: client_version (string)
        data.append(protoFieldString(2, clientVersion))
        // Field 3: os (string)
        data.append(protoFieldString(3, os))
        // Field 4: os_version (string)
        data.append(protoFieldString(4, osVersion))

        return data
    }
}

struct PlayerFeatures {
    var compressionBitrate: Int32 = 96000
    var hasMultiPayload: Bool = true
    var hasMessageFeature: Bool = true
    var hasStreamData: Bool = true
    var hasRetransmission: Bool = true
    var hasServerAudioConfig: Bool = true
}

struct ServerHello {
    let serverId: String
    let serverVersion: String
    let serverName: String
    let sampleRate: Int32
    let channelCount: Int32
    let bitrate: Int32
}

// MARK: - Low-level Protobuf Wire Format Helpers

/// Encodes a protobuf string field
func protoFieldString(_ fieldNumber: Int, _ value: String) -> Data {
    var data = Data()
    // Tag: field_number << 3 | wire_type (2 for length-delimited)
    data.append(protoVarint(UInt64(fieldNumber) << 3 | 2))
    // Length + value
    let utf8 = value.data(using: .utf8) ?? Data()
    data.append(protoVarint(UInt64(utf8.count)))
    data.append(utf8)
    return data
}

/// Encodes a protobuf int32 field
func protoFieldInt32(_ fieldNumber: Int, _ value: Int32) -> Data {
    var data = Data()
    // Tag: field_number << 3 | wire_type (0 for varint)
    data.append(protoVarint(UInt64(fieldNumber) << 3 | 0))
    data.append(protoVarint(UInt64(bitPattern: Int64(value))))
    return data
}

/// Encodes a protobuf int64 field
func protoFieldInt64(_ fieldNumber: Int, _ value: Int64) -> Data {
    var data = Data()
    data.append(protoVarint(UInt64(fieldNumber) << 3 | 0))
    data.append(protoVarint(UInt64(bitPattern: value)))
    return data
}

/// Encodes a protobuf bool field
func protoFieldBool(_ fieldNumber: Int, _ value: Bool) -> Data {
    var data = Data()
    data.append(protoVarint(UInt64(fieldNumber) << 3 | 0))
    data.append(value ? 1 : 0)
    return data
}

/// Encodes a protobuf bytes field
func protoFieldBytes(_ fieldNumber: Int, _ value: Data) -> Data {
    var data = Data()
    data.append(protoVarint(UInt64(fieldNumber) << 3 | 2))
    data.append(protoVarint(UInt64(value.count)))
    data.append(value)
    return data
}

/// Encodes a varint (variable-length integer)
func protoVarint(_ value: UInt64) -> Data {
    var data = Data()
    var v = value
    while v > 127 {
        data.append(UInt8(v & 0x7F | 0x80))
        v >>= 7
    }
    data.append(UInt8(v & 0x7F))
    return data
}
